---
title: "Lab11"
author: "R Kelly"
date: "4/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(babynames)
srcbabynames<-(babynames::babynames)
```

```{r}
#make your own version of the data by assigning a new variable to the srcbabynames data object
babynamesPersonal <- srcbabynames
babynames<-(babynames::babynames)
Megan <- filter(babynames,str_detect(babynames$name, "Megan")) %>% group_by(year) %>% summarize(sumprop=sum(prop))

ggplot(data=Megan) +
  geom_line(aes(x=year,y=sumprop)) +
  ggtitle("Total proportion of US babies named \"Megan\"")

```


###Lauren

```{r}
babynamesLauren <- babynamesPersonal
babynamesL<-(babynames::babynames)
Lauren <- filter(babynamesL,str_detect(babynamesL$name, "L[ao][^ie]r[ey]n+[^a]?$")) %>% group_by(year) %>% summarize(sumprop=sum(prop))

ggplot(data=Lauren) +
  geom_line(aes(x=year,y=sumprop)) +
  ggtitle("Total proportion of US babies named a version of \"Lauren\"")

Laurensincebirth <- filter(Lauren,year>1998)

ggplot(data=Laurensincebirth) +
  geom_line(aes(x=year,y=sumprop)) +
  ggtitle("Total proportion of US babies named a version of \"Lauren\" since 1998")

```

