

---
title: "Lab 12"
author: "Gregor, Ping, Sasha, Lauren, Peter"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
```



```{r}
library(tidyverse)
```


```{r}

gapminder<- gapminder::gapminder
samp <- sample(gapminder$lifeExp,300, replace = FALSE)
view(samp)
```


```{r}

```

```{r}

v1 <- gapminder$year
v2 <- gapminder$lifeExp
group1 <- samp[1:3]
group2 <- samp[3+1:300]

```



```{r}
perm_mean <- function(perms = 1000, values, n1)
{
  ## Variables ##
  # perms: The number of permutations 
  # values (num): 
  # n1 (int): Size of group 1
  ###############
  vec <- numeric(1000)
  # Step 1:
  # Create vector of zeroes of length "perms" to store
  # permuted mean differnces
  
  
  
  # Loop throught number of permutations
  for (i in c(1:perms))
  {
    # Step 2:
    # Randomly separate vector "values" into disjoint 
    # groups of size "n1" and "length(values) - n1" respectively
    
    samp <- sample(gapminder$lifeExp, 300, replace = FALSE)
    group1 <- samp[1:n1]
    group2 <- samp[n1+1:length(values)]
    
    # Step 3:
    # Compute the sample means for the two groups from 
    # step 2
    
    M1 = mean(group1)
    M2 = mean(group2)
    
    # Step 4: 
    # Compute the difference in sample means, store the
    # value in the vector from step 1
    
    diffmean = M1 - M2
    vec[[i]] <- diffmean
    
  }
  
  # Step 5:
  # Return new updated vector, created in step 1
  return(vec)
  
}
```

```{r}
test <-  perm_mean(1000, 300, 50)
print(test)
```

```{r}
perm_corr <- function(perms = 1000, v1, v2)
{
  ## Variables ##
  # perms: The number of permutations 
  # v1 : first correlation vector
  # v2 : second correlation vector
  ###############
  vec <- numeric(1000)
  # Step 1:
  # Create vector of zeroes of length "perms" to store
  # permuted mean differnces
  
  
  
  # Loop throught number of permutations
  for (i in c(1:perms))
  {
    # Step 2:
    mixedV2 <- sample(v2)
    # Step 3:
    # Compute the sample means for the two groups from 
    # step 2
    
    vec [[i]] <- cor(v1,mixedV2)
    
    # Step 4: 
    # Compute the difference in sample means, store the
    # value in the vector from step 1
    
    
    
  }
  
  # Step 5:
  # Return new updated vector, created in step 1
  return(vec)
  
}

```


```{r}

corTest <- perm_corr(1000, v1, v2)
print(corTest)
```









